type: septop
complex:
  setup:
    apply_rest: true
    rest_config:
      scale_torsions: true
      scale_nonbonded: true

  states:
    # REST2
    bm_b0: [1.00, 0.90, 0.82, 0.75, 0.69, 0.64, 0.60, 0.56, 0.53, 0.50, 0.53, 0.56, 0.60, 0.64, 0.69, 0.75, 0.82, 0.90, 1.00]

solution:
  setup:
    apply_rest: true
    rest_config:
      scale_torsions: true
      scale_nonbonded: true

  states:
    # REST2
    bm_b0: [1.00, 0.89, 0.80, 0.72, 0.66, 0.61, 0.57, 0.53, 0.50, 0.50, 0.53, 0.57, 0.61, 0.66, 0.72, 0.80, 0.89, 1.00]
